# Ubuntu 18.04 with Java 8 installed.

FROM ubuntu:18.04

MAINTAINER LOVE TANEJA, https://github.com/lovetaneja

# BELOW ARE THE DETAILS OF COMMANDS USED in RUN
# apt-get update: Updates the list of available packages and their versions.
# apt-get upgrade: Installs any newer versions of currently installed packages.
# apt-get install -y software-properties-common: Installs software in order to allow for independent vendor software sources, in particular the “add-apt-repository” command that is used in the next line.
# add-apt-repository ppa:webupd8team/java -y: Adds the PPA repository that contains Oracle Java 8, assuming yes to all queries.
# apt-get update: Again, updates the list of available packages and their versions. The reason for running an update again is that a new repository was just added and we want to refresh the list of available packages and their versions, including those in the new repository.
# echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections: The Java installer require you to accept a license before the installation begins. This line automates accepting the license.
# apt-get install -y oracle-java8-installer: Finally Java 8 can be installed! The -y flag runs the installation in a non-interactive mode, assuming that all questions are to be answered “yes.”
# apt-get clean: Cleans the local repository from retrieved package files.

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y  software-properties-common && \
    add-apt-repository ppa:webupd8team/java -y && \
    apt-get update && \
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections && \
    apt-get install -y oracle-java8-installer && \
    apt-get clean