version: "3.0"
services:
  web:
    image: jenkins/jenkins:lts
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 8G
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
      - 50000:50000
    volumes:
      - /home/docker/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock	      
    networks:
      - webnet
networks:
  webnet:
