# Use root/example as user/password credentials
version: '3.0'

services:

  db:
    image: mysql
    deploy:
      replicas: 2
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080